### ISSUE TITLE
Using ipware on localhost

### ISSUE THREAD

**Issue by luanfonceca** [un33k/django-ipware#39]
Hi folks, i am using it to get the `ip_address` of users on django, after that i get more info from third party sites like http://ipstack.com, etc. But when we ran it on localhost the ip returned from the `ipware` is `None`, there is any way to return my ip address on development environment?

If it return my real ip, that already should help.
I'm not sure if that makes sense, i'm just trying to figure out how to use it on localhost without adding specific code just for running on localhost or using a tunnel like http://ngrok.com.

Thanks in advance.

**Comment by wking** [comment]
You can fake an IP by setting [one of the headers][1] in your requests (e.g. with `curl -H 'X-Forwarded-For: 4.4.4.4' …`).  Alternatively, you can provide a knob to set [`IPWARE_PRIVATE_IP_PREFIX`][2] to an empty tuple if you're fine with your local IP.

[1]: https://github.com/un33k/django-ipware/tree/2.0.2#precedence-order
[2]: https://github.com/un33k/django-ipware/tree/2.0.2#private-prefixes

**Comment by luanfonceca** [comment]
Hi @wking, thanks for the response.

I tried to setup the `IP_WARE_PRIVATE_IP_PREFIX` for testing it out.
```
>>> from django.conf import settings
>>> print(settings.IPWARE_PRIVATE_IP_PREFIX)
()
>>> print(request._request.META.get('REMOTE_ADDR'))
'127.0.0.1'
>>> print(get_real_ip(request))
None
```

Sorry if i did something wrong, but still doesn't work.

**Comment by wking** [comment]
On Wed, Apr 18, 2018 at 01:42:03PM -0700, Luan Fonseca wrote:
> >>> print(get_real_ip(request))

That's part of the deprecated v1 API [1].  The v2 API is get_client_ip
[2].

  from django.conf import settings
  from django.http import HttpRequest
  from ipware import get_client_ip

  settings.IPWARE_PRIVATE_IP_PREFIX = ()
  request = HttpRequest()
  request.META['REMOTE_ADDR'] = '127.0.0.1'
  get_client_ip(request)
  # ('127.0.0.1', False)

The False is because 127.0.0.1 is (appropriately, in the
global-network context) not routable.

[1]: https://github.com/un33k/django-ipware/blob/2.0.2/docs/README-VER1.md#django-ipware-deprecated
[2]: https://github.com/un33k/django-ipware/tree/2.0.2#how-to-use

**Comment by un33k** [comment]
@luanfonceca you should use the latest api. `get_real_ip` and `get_ip` are deprecated.

Also, if you can move the QA to [StackOverflow.](https://stackoverflow.com/a/16203978/103734)
