### ISSUE TITLE
Feature request: allow to add custom http headers, also allow to disable some http headers

### ISSUE THREAD

**Issue by SadPencil** [un33k/django-ipware#64]
Some CDN providers provides custom HTTP header, to provide the client ip. Example: Aliyun CDN, which providing `HTTP_ALI_CDN_REAL_IP` header.

Some CDN providers only use a subset of the HTTP header of what your library provides. In this situation, malicious users could make faked ip through these headers.

So, it's best to allow developers specify the HTTP headers that can be used to determine the IP, the list of which is configured *per CDN provider*. 
Example:
```python
request_header_list= [
'HTTP_ALI_CDN_REAL_IP',
'HTTP_X_FORWARDED_FOR',
'REMOTE_ADDR'
]
```
So that the IP address can be obtained while the security is enforced for advanced developers.

----

After checking the existing source code, this feature is already implemented through `request_header_order`. 

However,
- Document about this feature can be provided.
- `request_header_list` is a better name than `request_header_order`.

**Comment by un33k** [comment]
Please define `IPWARE_META_PRECEDENCE_ORDER` in your settings.py so you don't have to pass it via the api call.  Then add any order or custom headers you may need. 

Here is the readme. https://github.com/un33k/django-ipware#precedence-order

As far as the naming goes, some PRs are from contributors, and the naming things is hard. With that said, due to backward compatibility, the naming stands as is.

**Comment by un33k** [comment]
@SadPencil django-ipware is on its way to being deprecated.

With that said, I have a python package that is going to replace it.

Have a look at [python-ipware](https://github.com/un33k/django-ipware) and if works for you switch to it.

Feedback is welcomed.
